#Text Size
FONT = 'Helvetica'
TITLE_TEXT_SIZE = 30
WIDGET_TEXT_SIZE = 50

#Colors
MINT_GREEN = '#ABFBBB'
TURQUOISE_GREEN = '#1E5945'


GREEN ='#50BFAB'
DARK_GREEN ='#3A8A7A'
WHITE ='#F2F2F2'
BLACK ='#1F1F1F'
LIGHT_GRAY ='#E8E8E8'
GRAY ='#D9D9D9'